version: '3.8'

services:
  transcode-docker:
    build: .
    container_name: transcode-docker
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run dev
    restart: always
    security_opt:
      - no-new-privileges:true
